In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import re 
import string

In [2]:
d_fake = pd.read_csv('Fake.csv')
d_true = pd.read_csv('True.csv')

In [3]:
d_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
d_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [5]:
d_fake["class"] = 0
d_true["class"] = 1

In [6]:
d_fake.shape, d_true.shape

((23481, 5), (21417, 5))

In [13]:
d_fake_man_test = d_fake.tail(10)
for i in range(23480,23470,-1):
    d_fake.drop([i],axis =0, inplace = True)

d_true_man_test = d_true.tail(10)
for i in range(21416,21406,-1):
    d_true.drop([i],axis =0, inplace = True )

In [14]:
d_fake.shape,d_true.shape

((23471, 5), (21407, 5))

In [15]:
d_fake_man_test["class"]=0
d_true_man_test["class"]=1

C:\Users\thaku\AppData\Local\Temp\ipykernel_17876\1268992845.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_fake_man_test["class"]=0
C:\Users\thaku\AppData\Local\Temp\ipykernel_17876\1268992845.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  d_true_man_test["class"]=1

In [16]:
d_fake_man_test.head

<bound method NDFrame.head of                                                    title  \
23471  Seven Iranians freed in the prisoner swap have...
23472                      #Hashtag Hell & The Fake Left
23473  Astroturfing: Journalist Reveals Brainwashing ...
23474          The New American Century: An Era of Fraud
23475  Hillary Clinton: ‘Israel First’ (and no peace ...
23476  McPain: John McCain Furious That Iran Treated ...
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...
23479  How to Blow $700 Million: Al Jazeera America F...
23480  10 U.S. Navy Sailors Held by Iranian Military ...

                                                    text      subject  \
23471  21st Century Wire says This week, the historic...  Middle-east
23472   By Dady Chery and Gilbert MercierAll writers ...  Middle-east
23473  Vic Bishop Waking TimesOur reality is carefull...  Middle-east
23474  Paul Craig RobertsIn the last years of the 20t...  Middle-east
23475  Robert Fantina CounterpunchAlthough the United...  Middle-east
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east
23477  21st Century Wire says It s a familiar theme. ...  Middle-east
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east
23479  21st Century Wire says Al Jazeera America will...  Middle-east
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east

                   date  class
23471  January 20, 2016      0
23472  January 19, 2016      0
23473  January 19, 2016      0
23474  January 19, 2016      0
23475  January 18, 2016      0
23476  January 16, 2016      0
23477  January 16, 2016      0
23478  January 15, 2016      0
23479  January 14, 2016      0
23480  January 12, 2016      0  >

In [17]:
d_true_man_test.head

<bound method NDFrame.head of                                                    title  \
21407  Mata Pires, owner of embattled Brazil builder ...
21408  U.S., North Korea clash at U.N. forum over nuc...
21409  U.S., North Korea clash at U.N. arms forum on ...
21410  Headless torso could belong to submarine journ...
21411  North Korea shipments to Syria chemical arms a...
21412  'Fully committed' NATO backs new U.S. approach...
21413  LexisNexis withdrew two products from Chinese ...
21414  Minsk cultural hub becomes haven from authorities
21415  Vatican upbeat on possibility of Pope Francis ...
21416  Indonesia to buy $1.14 billion worth of Russia...

                                                    text    subject  \
21407  SAO PAULO (Reuters) - Cesar Mata Pires, the ow...  worldnews
21408  GENEVA (Reuters) - North Korea and the United ...  worldnews
21409  GENEVA (Reuters) - North Korea and the United ...  worldnews
21410  COPENHAGEN (Reuters) - Danish police said on T...  worldnews
21411  UNITED NATIONS (Reuters) - Two North Korean sh...  worldnews
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...  worldnews
21413  LONDON (Reuters) - LexisNexis, a provider of l...  worldnews
21414  MINSK (Reuters) - In the shadow of disused Sov...  worldnews
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews

                   date  class
21407  August 22, 2017       1
21408  August 22, 2017       1
21409  August 22, 2017       1
21410  August 22, 2017       1
21411  August 21, 2017       1
21412  August 22, 2017       1
21413  August 22, 2017       1
21414  August 22, 2017       1
21415  August 22, 2017       1
21416  August 22, 2017       1  >

In [18]:
data_merge = pd.concat([d_fake,d_true],axis=0)
data_merge.head

<bound method NDFrame.head of                                                    title  \
0       Donald Trump Sends Out Embarrassing New Year’...
1       Drunk Bragging Trump Staffer Started Russian ...
2       Sheriff David Clarke Becomes An Internet Joke...
3       Trump Is So Obsessed He Even Has Obama’s Name...
4       Pope Francis Just Called Out Donald Trump Dur...
...                                                  ...
21402  Exclusive: Trump's Afghan decision may increas...
21403  U.S. puts more pressure on Pakistan to help wi...
21404  Exclusive: U.S. to withhold up to $290 million...
21405  Trump talks tough on Pakistan's 'terrorist' ha...
21406  U.S., North Korea clash at U.N. forum over nuc...

                                                    text    subject  \
0      Donald Trump just couldn t wish all Americans ...       News
1      House Intelligence Committee Chairman Devin Nu...       News
2      On Friday, it was revealed that former Milwauk...       News
3      On Christmas day, Donald Trump announced that ...       News
4      Pope Francis used his annual Christmas Day mes...       News
...                                                  ...        ...
21402  ON BOARD A U.S. MILITARY AIRCRAFT (Reuters) - ...  worldnews
21403  WASHINGTON (Reuters) - The United States sugge...  worldnews
21404  WASHINGTON (Reuters) - The United States has d...  worldnews
21405  ISLAMABAD (Reuters) - Outlining a new strategy...  worldnews
21406  GENEVA (Reuters) - North Korea and the United ...  worldnews

                    date  class
0      December 31, 2017      0
1      December 31, 2017      0
2      December 30, 2017      0
3      December 29, 2017      0
4      December 25, 2017      0
...                  ...    ...
21402   August 22, 2017       1
21403   August 21, 2017       1
21404   August 22, 2017       1
21405   August 22, 2017       1
21406   August 22, 2017       1

[44878 rows x 5 columns]>

In [19]:
data_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [21]:
data = data_merge.drop(['title','subject','date'],axis=1)

In [22]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [23]:
data = data.sample(frac=1)

In [24]:
data.head

<bound method NDFrame.head of                                                     text  class
5614   A citizen from the United Arab Emirates (UAE) ...      0
10696  MSNBC host Thomas Roberts on Sunday was specul...      0
2522   BERLIN (Reuters) - Plans under consideration i...      1
1153   Donald Trump went on a whining rant about the ...      0
17130                THE GREAT QUESTION OF CITIZENSHIP        0
...                                                  ...    ...
8463   British comic Peter Serafinowicz has made ever...      0
14781  BEIJING (Reuters) - A trip to Beijing last wee...      1
18019  WELLINGTON (Reuters) - The party holding the b...      1
2032   WASHINGTON (Reuters) - U.S. House of Represent...      1
8835   WASHINGTON (Reuters) - Donald Trump endured so...      1

[44878 rows x 2 columns]>

In [26]:
data.reset_index(inplace=True)
data.drop(['index'],axis=1,inplace=True)

In [27]:
data.columns

Index(['level_0', 'text', 'class'], dtype='object')

In [28]:
data.head

<bound method NDFrame.head of        level_0                                               text  class
0            0  A citizen from the United Arab Emirates (UAE) ...      0
1            1  MSNBC host Thomas Roberts on Sunday was specul...      0
2            2  BERLIN (Reuters) - Plans under consideration i...      1
3            3  Donald Trump went on a whining rant about the ...      0
4            4                THE GREAT QUESTION OF CITIZENSHIP        0
...        ...                                                ...    ...
44873    44873  British comic Peter Serafinowicz has made ever...      0
44874    44874  BEIJING (Reuters) - A trip to Beijing last wee...      1
44875    44875  WELLINGTON (Reuters) - The party holding the b...      1
44876    44876  WASHINGTON (Reuters) - U.S. House of Represent...      1
44877    44877  WASHINGTON (Reuters) - Donald Trump endured so...      1

[44878 rows x 3 columns]>

In [30]:
def wordopt(text):
    text = text.lower()
    text = re.sub('\[.*?\]','',text)
    text = re.sub("\\W"," ",text)
    text = re.sub('https?://\S+|www\.\S+','',text)
    text = re.sub('<.*?>+','',text)
    text = re.sub('[%s]'%re.escape(string.punctuation),'',text)
    text = re.sub('\n','',text)
    text = re.sub('\w*\d\w*','',text)
    return text

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\['
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:9: SyntaxWarning: invalid escape sequence '\w'
C:\Users\thaku\AppData\Local\Temp\ipykernel_17876\3988158203.py:3: SyntaxWarning: invalid escape sequence '\['
  text = re.sub('\[.*?\]','',text)
C:\Users\thaku\AppData\Local\Temp\ipykernel_17876\3988158203.py:5: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub('https?://\S+|www\.\S+','',text)
C:\Users\thaku\AppData\Local\Temp\ipykernel_17876\3988158203.py:9: SyntaxWarning: invalid escape sequence '\w'
  text = re.sub('\w*\d\w*','',text)

In [31]:
data['text']=data['text'].apply(wordopt)

In [32]:
x = data['text']
y = data['class']

In [33]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [36]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [37]:
pred_lr = LR.predict(xv_test)

In [38]:
LR.score(xv_test,y_test)

0.9867201426024955

In [40]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5888
           1       0.98      0.99      0.99      5332

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [41]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [42]:
pred_dt = DT.predict(xv_test)

In [43]:
DT.score(xv_test,y_test)

0.9954545454545455

In [44]:
print(classification_report(y_test,pred_dt))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      5888
           1       1.00      0.99      1.00      5332

    accuracy                           1.00     11220
   macro avg       1.00      1.00      1.00     11220
weighted avg       1.00      1.00      1.00     11220

In [47]:
from sklearn.ensemble import GradientBoostingClassifier
GB = GradientBoostingClassifier(random_state=0)
GB.fit(xv_train,y_train)

GradientBoostingClassifier(random_state=0)

In [48]:
predict_gb = GB.predict(xv_test)

In [49]:
GB.score(xv_test,y_test)

0.9943850267379679

In [50]:
print(classification_report(y_test,predict_gb))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      5888
           1       0.99      1.00      0.99      5332

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [51]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(random_state=0)
RF.fit(xv_train,y_train)

RandomForestClassifier(random_state=0)

In [52]:
predict_rf = RF.predict(xv_test)

In [53]:
RF.score(xv_test,y_test)

0.990463458110517

In [54]:
print(classification_report(y_test,predict_rf))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5888
           1       0.99      0.99      0.99      5332

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [59]:
def output_label(n):
    if n==0:
        return "Fake News"
    elif n==1:
        return "Not A Fake News"
    
def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] =  new_def_test["text"].apply(wordopt)
    new_x_test = new_def_test["text"]
    new_xv_test = vectorization.transform(new_x_test)
    pred_lr = LR.predict(new_xv_test)
    pred_dt = DT.predict(new_xv_test)
    predict_gb = GB.predict(new_xv_test)
    predict_rf = RF.predict(new_xv_test)
    return print("\n\nLR Prediction:{}\nDT Prediction:{}\nGB Prediction:{}\nRF Prediction:{}".format(output_label(pred_lr[0]), output_label(pred_dt[0]), output_label(predict_gb[0]), output_label(predict_rf[0])))

In [64]:
news = str(input())
manual_testing(news)

LR Prediction:Fake News
DT Prediction:Fake News
GB Prediction:Fake News
RF Prediction:Fake News